"use client";
import { useRef,useState } from "react";
import { useLanguage } from "@/components/language";
import { launch } from "@/lib/store-config";
import { business } from "@/config/business";
export function WithdrawalForm(){
 const {lang}=useLanguage(); const [review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(false),[receipt,setReceipt]=useState("");const id=useRef("");
 const [data,setData]=useState({name:"",email:"",order:"",items:""});
 const t={EN:["Withdraw from contract","Full name","Email for confirmation","Order or payment reference","Items you wish to return","Review withdrawal","Confirm withdrawal","Edit","Request recorded. Save this reference:","We could not record the request. Try again or contact the seller by email.","Online withdrawal opens with sales. You can also notify the seller by email; this form is not mandatory.","Withdrawal does not immediately cancel a payment. We will review the request and send a receipt by email."],HU:["Elállás a szerződéstől","Teljes név","E-mail a visszaigazoláshoz","Rendelési vagy fizetési azonosító","Mely termékektől állsz el?","Elállás áttekintése","Elállás megerősítése","Módosítás","Kérelem rögzítve. Őrizd meg az azonosítót:","Nem sikerült rögzíteni. Próbáld újra vagy jelezd e-mailben az eladónak.","Az online elállás az értékesítéssel nyílik meg. E-mailben is jelezheted az elállást; az űrlap használata nem kötelező.","Az elállás nem vonja vissza azonnal a fizetést. A kérelmet feldolgozzuk és e-mailes átvételi visszaigazolást küldünk."],DE:["Vertrag widerrufen","Vollständiger Name","E-Mail für die Bestätigung","Bestell- oder Zahlungsreferenz","Zu widerrufende Artikel","Widerruf prüfen","Widerruf bestätigen","Bearbeiten","Anfrage erfasst. Bitte speichere diese Referenz:","Anfrage konnte nicht gespeichert werden. Versuche es erneut oder kontaktiere den Verkäufer per E-Mail.","Der Online-Widerruf öffnet mit dem Verkauf. Du kannst den Verkäufer auch per E-Mail informieren; das Formular ist nicht verpflichtend.","Der Widerruf storniert die Zahlung nicht sofort. Wir bearbeiten die Anfrage und senden eine Eingangsbestätigung per E-Mail."]}[lang];
 if(receipt)return <div role="status"><p>{t[8]} <strong>{receipt}</strong></p><p>{t[11]}</p></div>;
 return <div><h2>{t[0]}</h2>{!launch.withdrawalEnabled?<p>{t[10]}</p>:<form className="withdrawal-form" onSubmit={async e=>{e.preventDefault();if(!review){setReview(true);return}if(busy)return;setBusy(true);setError(false);try{if(!id.current)id.current=crypto.randomUUID();const r=await fetch("/api/withdrawal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,language:lang,requestId:id.current,confirm:true}),signal:AbortSignal.timeout(15000)});const result=await r.json() as {reference?:string};if(!r.ok||!result.reference)throw Error();setReceipt(result.reference)}catch{setError(true)}finally{setBusy(false)}}}>
 {(["name","email","order","items"] as const).map((key,i)=><label key={key}>{t[i+1]}<input type={key==="email"?"email":"text"} required maxLength={key==="items"?1500:key==="email"?254:150} value={data[key]} readOnly={review} onChange={e=>{setData({...data,[key]:e.target.value});id.current=""}}/></label>)}
 {review&&<p>{t[11]}</p>}<button className="primary" disabled={busy}>{review?t[6]:t[5]}</button>{review&&<button type="button" onClick={()=>setReview(false)}>{t[7]}</button>}{error&&<p role="alert">{t[9]}</p>}</form>}{business.email&&<p><a href={`mailto:${business.email}`}>{business.email}</a></p>}</div>;
}
