import { business } from "../config/business.ts";
export type PolicyLanguage = "EN"|"HU"|"DE";
type Section = [string,string];
const placeholder = {EN:"Not yet configured. Sales remain closed.",HU:"Még nincs kitöltve. Az értékesítés zárva marad.",DE:"Noch nicht eingerichtet. Der Verkauf bleibt geschlossen."};
export function policies(lang: PolicyLanguage): Record<string,Section[]> {
 const missing=placeholder[lang]; const v=(s:string)=>s||missing;
 const common:Section[] = [[{EN:"Seller and contact",HU:"Eladó és elérhetőségek",DE:"Verkäufer und Kontakt"}[lang],`${v(business.legalName)} | ${v(business.legalForm)} | ${v(business.address)} | ${v(business.email)} | ${v(business.phone)}`]];
 const terms:Record<PolicyLanguage,Section[]> = {
 EN:[
 ["Scope and ordering","These terms cover consumer purchases of FLOWSTATE RACING clothing and accessories. Choose the product, size and quantity, then check the cart and delivery option. You can correct errors before continuing to Stripe. Only the final payment button on the provider page places an order with an obligation to pay. No account is required. The contract is concluded when the seller confirms acceptance by email after verified payment. An automatic payment receipt alone is not acceptance. If an order cannot be accepted, the payment will be refunded."],
 ["Prices and payment",`Checkout uses HUF. The total includes the displayed shipping cost. EUR figures on product cards are indicative, not the charged amount. ${v(business.vatStatement.EN)} Payment is processed by Stripe. Your bank may charge conversion fees. No payment-card details are stored by this storefront.`],
 ["Preorders and delivery",`${v(business.deliveryStatement.EN)} Latest agreed delivery: ${v(business.latestDeliveryDate)}. A preorder means production follows the sales window. It does not remove withdrawal or defect rights. Shipping destinations and methods are limited to those available at checkout. Contact the seller about delay, loss or damage; statutory remedies remain available.`],
 ["Contract record and language","English, Hungarian and German are available. Save the confirmation email and terms supplied with it. Orders are recorded electronically by the seller; no customer account or public order lookup is provided. Changes to the website do not retrospectively change your confirmed order. Mandatory consumer protections applicable to your purchase remain unaffected."],
 ["Withdrawal and defects","The withdrawal and delivery page forms part of these terms. Ordinary clothing with a standard design is not automatically personalised because it is made after a preorder. Rights for faulty goods are separate from a change-of-mind return. Clothing shown here is streetwear, not certified motorcycle protective equipment."],
 ["Complaints",`Send complaints to ${v(business.email)} or ${v(business.complaintAddress)}. Conciliation body: ${v(business.conciliationBody)}; ${v(business.conciliationContact)}. Consumers may use the competent authority, alternative dispute resolution or courts. No compulsory waiver of these rights applies.`]],
 HU:[
 ["Hatály és rendelés","A feltételek a FLOWSTATE RACING ruházat és kiegészítők fogyasztói vásárlására vonatkoznak. Válaszd ki a terméket, méretet, mennyiséget és szállítást. A kosarat a Stripe oldalára lépés előtt javíthatod. Fizetési kötelezettséget a szolgáltató végső fizetési gombja hoz létre. Regisztráció nem szükséges. A szerződés az ellenőrzött fizetést követő, eladó által küldött elfogadó e-maillel jön létre. Az automatikus fizetési bizonylat önmagában nem elfogadás. Ha a rendelés nem teljesíthető, a befizetést visszatérítjük."],
 ["Árak és fizetés",`A terhelés pénzneme HUF. A végösszeg tartalmazza a kijelzett szállítást. A termékkártyák eurós ára tájékoztató jellegű. ${v(business.vatStatement.HU)} A fizetést a Stripe kezeli. A bankod átváltási díjat számíthat fel. Az oldal nem tárol bankkártyaadatot.`],
 ["Előrendelés és szállítás",`${v(business.deliveryStatement.HU)} Vállalt legkésőbbi kézbesítés: ${v(business.latestDeliveryDate)}. Előrendelésnél a gyártás a rendelési időszak után indul. Ettől az elállási és hibás teljesítési jogok megmaradnak. A választható országokat és módokat a pénztár mutatja. Késés, elveszett vagy sérült küldemény esetén keresd az eladót; a törvényes jogaidat ez nem korlátozza.`],
 ["Szerződés és nyelv","Angol, magyar és német nyelv érhető el. Őrizd meg a visszaigazoló e-mailt és a vele küldött feltételeket. Az eladó elektronikusan nyilvántartja a rendelést; ügyfélfiók és nyilvános rendeléslekérdezés nincs. A honlap későbbi változása nem módosítja visszamenőleg a visszaigazolt rendelést. A kötelező fogyasztóvédelmi szabályok változatlanul alkalmazandók."],
 ["Elállás és hibák","A szállítási és elállási tájékoztató a feltételek része. A standard mintájú, előrendelés után gyártott ruha nem lesz ettől automatikusan személyre szabott termék. A hibás teljesítés miatti igény különbözik az indokolás nélküli elállástól. A ruházat utcai viselet, nem minősített motoros védőfelszerelés."],
 ["Panaszkezelés",`Panasz: ${v(business.email)} vagy ${v(business.complaintAddress)}. Békéltető testület: ${v(business.conciliationBody)}; ${v(business.conciliationContact)}. A fogyasztó az illetékes hatósághoz, békéltető testülethez vagy bírósághoz fordulhat; ezekről a jogokról nem kell lemondania.`]],
 DE:[
 ["Bestellung und Vertrag","Diese Bedingungen gelten für Verbraucherkäufe von FLOWSTATE RACING Kleidung und Accessoires. Wähle Artikel, Größe, Menge und Versand. Vor der Weiterleitung zu Stripe kannst du den Warenkorb korrigieren. Erst der abschließende Zahlungsbutton beim Anbieter löst eine zahlungspflichtige Bestellung aus. Ein Konto ist nicht erforderlich. Der Vertrag entsteht durch die Annahmebestätigung des Verkäufers per E-Mail nach geprüfter Zahlung. Ein automatischer Zahlungsbeleg allein ist keine Annahme. Nicht angenommene Bestellungen werden erstattet."],
 ["Preise und Zahlung",`Die Abrechnung erfolgt in HUF, einschließlich der angezeigten Versandkosten. Europreise auf Produktkarten dienen nur der Orientierung. ${v(business.vatStatement.DE)} Stripe verarbeitet die Zahlung. Deine Bank kann Umrechnungsgebühren berechnen. Der Shop speichert keine Kartendaten.`],
 ["Vorbestellung und Lieferung",`${v(business.deliveryStatement.DE)} Spätester vereinbarter Liefertermin: ${v(business.latestDeliveryDate)}. Die Produktion beginnt nach dem Bestellfenster. Widerrufs- und Mängelrechte bleiben bestehen. Lieferländer und Versandarten werden im Checkout angezeigt. Bei Verzögerung, Verlust oder Beschädigung kontaktiere den Verkäufer. Gesetzliche Rechte bleiben unberührt.`],
 ["Vertragsspeicherung und Sprache","Englisch, Ungarisch und Deutsch stehen zur Verfügung. Bewahre die Bestätigung und die mitgesendeten Bedingungen auf. Der Verkäufer erfasst Bestellungen elektronisch; ein Kundenkonto oder eine öffentliche Bestellabfrage gibt es nicht. Spätere Änderungen der Website ändern bestätigte Bestellungen nicht rückwirkend. Zwingender Verbraucherschutz bleibt anwendbar."],
 ["Widerruf und Mängel","Die Versand- und Widerrufshinweise sind Teil dieser Bedingungen. Kleidung mit Standardmotiv wird durch Fertigung nach Vorbestellung nicht automatisch personalisiert. Mängelrechte bestehen unabhängig vom Widerruf. Die Kleidung ist Streetwear und keine zertifizierte Motorradschutzkleidung."],
 ["Beschwerden",`Kontakt: ${v(business.email)} oder ${v(business.complaintAddress)}. Schlichtungsstelle: ${v(business.conciliationBody)}; ${v(business.conciliationContact)}. Verbraucher können zuständige Behörden, Schlichtungsstellen oder Gerichte einschalten. Ein Verzicht auf diese Rechte wird nicht verlangt.`]]};
 const withdrawal:Record<PolicyLanguage,Section[]> = {
 EN:[["Withdrawal","For ordinary online clothing purchases you may withdraw without giving a reason within 14 days of receiving the goods. Send an unambiguous notice by email or use the online withdrawal form. Sending the notice before the deadline is sufficient. Return the goods within 14 days after notifying us. You bear direct return costs if informed of this before purchase. Faulty goods follow separate statutory rules."],["Refunds","We refund the payment, including the least expensive standard outbound delivery offered, within 14 days of notification. We may withhold reimbursement until the goods are returned or you provide evidence of dispatch, whichever comes first. Refunds use the original payment method unless otherwise agreed without fees to you. You are liable only for diminished value caused by handling beyond what is needed to inspect the goods."],["Return address",v(business.returnAddress)],["Model withdrawal notice","To the seller: I withdraw from the contract for the following goods: [items]. Ordered/received on: [dates]. Consumer name and address: [details]. Date: [date]. Signature only if sent on paper. This model is optional."],["Faulty goods","Statutory conformity rights are separate from withdrawal. Depending on the applicable law and circumstances, remedies include repair or replacement and, where the legal conditions are met, price reduction or termination. Report the issue with the order reference and a description. A limited drop does not remove statutory rights."]],
 HU:[["Elállás","Szokásos online ruhavásárlásnál az átvételtől számított 14 napon belül indokolás nélkül elállhatsz. Küldj egyértelmű nyilatkozatot e-mailben, vagy használd az online űrlapot. Elég a határidő lejárta előtt elküldeni. A nyilatkozat után 14 napon belül küldd vissza a terméket. A visszaküldés közvetlen költsége téged terhel, ha erről vásárlás előtt tájékoztattunk. Hibás terméknél külön törvényi szabályok érvényesek."],["Visszatérítés","A befizetést és a felkínált legolcsóbb szokásos kiszállítás díját az elállás közlésétől számított 14 napon belül visszatérítjük. A visszatérítés a termék vagy a feladási igazolás megérkezéséig visszatartható, a korábbi időpontig. Az eredeti fizetési módot használjuk, kivéve ha díjmentes eltérő megoldásban állapodunk meg. Csak a szükséges kipróbálást meghaladó használatból eredő értékcsökkenésért felelsz."],["Visszaküldési cím",v(business.returnAddress)],["Elállási nyilatkozatminta","Az eladónak: elállok az alábbi termékek adásvételétől: [termékek]. Rendelés/átvétel ideje: [dátumok]. Fogyasztó neve és címe: [adatok]. Dátum: [dátum]. Aláírás csak papíron küldött nyilatkozat esetén. A minta használata nem kötelező."],["Hibás teljesítés","A kellékszavatossági és más kötelező igények az elállástól függetlenek. A jogszabályi feltételek szerint kijavítás vagy kicserélés, illetve adott esetben árleszállítás vagy szerződésmegszüntetés kérhető. A hibát rendelési azonosítóval és leírással jelezd. A limitált kollekció nem vonja el a törvényes jogokat."]],
 DE:[["Widerruf","Bei gewöhnlichen Online-Kleidungskäufen kannst du innerhalb von 14 Tagen ab Erhalt ohne Begründung widerrufen. Sende eine eindeutige Erklärung per E-Mail oder nutze das Onlineformular. Die rechtzeitige Absendung genügt. Sende die Ware innerhalb von 14 Tagen nach Erklärung zurück. Du trägst direkte Rücksendekosten, wenn du vor dem Kauf darüber informiert wurdest. Für mangelhafte Ware gelten gesonderte gesetzliche Regeln."],["Erstattung","Wir erstatten die Zahlung einschließlich der günstigsten angebotenen Standardlieferung innerhalb von 14 Tagen nach Mitteilung. Bis zum Wareneingang oder Versandnachweis, je nachdem was früher eintritt, kann die Erstattung zurückgehalten werden. Es gilt das ursprüngliche Zahlungsmittel, sofern nichts anderes ohne Kosten für dich vereinbart wurde. Du haftest nur für Wertverlust durch Umgang, der über die nötige Prüfung hinausgeht."],["Rücksendeadresse",v(business.returnAddress)],["Mustererklärung","An den Verkäufer: Hiermit widerrufe ich den Kauf folgender Waren: [Artikel]. Bestellt/erhalten am: [Datum]. Name und Anschrift: [Angaben]. Datum: [Datum]. Unterschrift nur auf Papier. Die Nutzung dieses Musters ist freiwillig."],["Mängelrechte","Gesetzliche Rechte bei mangelhafter Ware bestehen unabhängig vom Widerruf. Je nach anwendbarem Recht und Voraussetzungen kommen Reparatur oder Ersatz sowie gegebenenfalls Preisminderung oder Vertragsbeendigung in Betracht. Melde Mängel mit Bestellreferenz und Beschreibung. Eine limitierte Auflage schränkt gesetzliche Rechte nicht ein."]]
 };
 const privacy:Record<PolicyLanguage,Section[]> = {
 EN:[["Controller",`${v(business.legalName)}, ${v(business.address)}. Privacy contact: ${v(business.privacyContact)}.`],["Purposes and legal bases","Orders, contact and delivery use the data necessary for your contract or requested pre-contractual steps. Tax and accounting records are processed to meet legal obligations. Proportionate security and fraud controls serve legitimate interests, subject to your rights. Optional drop emails use separate, withdrawable consent and email confirmation. A purchase is not newsletter consent."],["Data and recipients","Order references, selected products, prices, language and terms version are stored in Cloudflare D1. Stripe processes payment, billing and delivery details. Brevo sends requested service messages and confirmed newsletter emails. Withdrawal requests store your name, email, reference and selected goods. The store does not retain card numbers. Carrier and invoicing providers receive only necessary information. No customer records belong in the public source repository."],["Processors and transfers",v(business.processorStatement.EN)],["Retention",v(business.retentionStatement.EN)],["Your rights",`Where applicable, request access, correction, erasure, restriction, portability or object to legitimate-interest processing via ${v(business.privacyContact)}. Withdraw marketing consent via the unsubscribe link. Withdrawal does not affect earlier lawful processing. Identity may be verified proportionately. You can complain to NAIH (https://www.naih.hu/) or your competent supervisory authority. No solely automated decisions producing legal or similarly significant effects are intended.`],["Required information and storage","Contract data is needed to process an order; marketing signup is optional. Local cart and language storage are described on the cookies page. Providers process technical connection data to deliver and secure their services. No advertising or analytics scripts are installed."]],
 HU:[["Adatkezelő",`${v(business.legalName)}, ${v(business.address)}. Adatvédelmi elérhetőség: ${v(business.privacyContact)}.`],["Célok és jogalapok","A rendelés, kapcsolattartás és szállítás adatait a szerződés vagy a kérésedre történő előkészítés teljesítéséhez kezeljük. A számlázási és számviteli adatok kezelése jogi kötelezettség. Az arányos biztonsági és visszaélés-megelőzési intézkedések jogos érdeken alapulnak, a jogaid figyelembevételével. A drop-hírlevél külön, visszavonható hozzájárulással és e-mailes megerősítéssel működik. A vásárlás nem hírlevél-hozzájárulás."],["Adatok és címzettek","A rendelési azonosító, termékek, árak, nyelv és feltételverzió a Cloudflare D1-ben tárolódik. A Stripe kezeli a fizetési, számlázási és szállítási adatokat. A Brevo küldi a kért ügyleti üzeneteket és a megerősített hírlevelet. Az elállási kérelem nevet, e-mailt, azonosítót és termékmegjelölést tartalmaz. Kártyaszámot az oldal nem tárol. A fuvarozó és számlázó csak a szükséges adatokat kapja meg. Ügyféladat nem kerülhet a nyilvános forráskódba."],["Adatfeldolgozók és adattovábbítás",v(business.processorStatement.HU)],["Megőrzés",v(business.retentionStatement.HU)],["Jogaid",`Alkalmazhatóság esetén hozzáférést, helyesbítést, törlést, korlátozást, hordozhatóságot kérhetsz vagy tiltakozhatsz a jogos érdeken alapuló kezelés ellen: ${v(business.privacyContact)}. A hírlevél-hozzájárulást a leiratkozó linken visszavonhatod, ez a korábbi jogszerű kezelést nem érinti. Arányos személyazonosítás szükséges lehet. Panasz: NAIH (https://www.naih.hu/) vagy a lakóhelyed szerint illetékes felügyeleti hatóság. Jogi vagy hasonlóan jelentős hatású, kizárólag automatizált döntést nem tervezünk.`],["Szükséges adatok és tárolás","A szerződéses adatok nélkül a rendelés nem teljesíthető; a hírlevél önkéntes. A helyi kosár- és nyelvtárolást a sütitájékoztató írja le. A szolgáltatók a működtetéshez és védelemhez technikai adatokat kezelnek. Reklám- és analitikai kód nincs telepítve."]],
 DE:[["Verantwortlicher",`${v(business.legalName)}, ${v(business.address)}. Datenschutzkontakt: ${v(business.privacyContact)}.`],["Zwecke und Rechtsgrundlagen","Bestellung, Kontakt und Lieferung erfolgen zur Vertragserfüllung oder auf deinen Wunsch zur Vorbereitung. Steuer- und Buchhaltungsdaten werden aufgrund rechtlicher Pflichten verarbeitet. Angemessene Sicherheits- und Betrugsschutzmaßnahmen beruhen auf berechtigten Interessen unter Beachtung deiner Rechte. Drop-E-Mails benötigen eine getrennte, widerrufliche Einwilligung mit E-Mail-Bestätigung. Ein Kauf ist keine Newsletter-Einwilligung."],["Daten und Empfänger","Bestellreferenz, Artikel, Preise, Sprache und Bedingungsversion werden in Cloudflare D1 gespeichert. Stripe verarbeitet Zahlungs-, Rechnungs- und Lieferdaten. Brevo versendet angeforderte Servicenachrichten und bestätigte Newsletter. Widerrufsanfragen enthalten Name, E-Mail, Referenz und Artikel. Der Shop speichert keine Kartennummern. Versand- und Rechnungsanbieter erhalten nur erforderliche Daten. Kundendaten gehören nicht in das öffentliche Quellcode-Repository."],["Dienstleister und Übermittlungen",v(business.processorStatement.DE)],["Speicherdauer",v(business.retentionStatement.DE)],["Deine Rechte",`Soweit anwendbar kannst du Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit oder Widerspruch gegen Verarbeitung aufgrund berechtigter Interessen verlangen: ${v(business.privacyContact)}. Marketingeinwilligung kannst du über den Abmeldelink widerrufen. Frühere rechtmäßige Verarbeitung bleibt unberührt. Eine angemessene Identitätsprüfung kann nötig sein. Beschwerdestelle: NAIH (https://www.naih.hu/) oder deine zuständige Aufsichtsbehörde. Ausschließlich automatisierte Entscheidungen mit rechtlicher oder vergleichbar erheblicher Wirkung sind nicht vorgesehen.`],["Erforderliche Daten und Speicherung","Ohne Vertragsdaten kann die Bestellung nicht ausgeführt werden; Newsletter sind freiwillig. Die Cookie-Seite erklärt lokalen Warenkorb- und Sprachspeicher. Anbieter verarbeiten technische Verbindungsdaten für Betrieb und Sicherheit. Werbe- und Analyseskripte sind nicht installiert."]]
 };
 return {TERMS:[...common,...terms[lang]], DELIVERY:[...common,...withdrawal[lang]], PRIVACY:privacy[lang], IMPRINT:[...common,[{EN:"Registration and tax",HU:"Nyilvántartás és adózás",DE:"Register und Steuern"}[lang],`${v(business.registrationAuthority)} | ${v(business.registrationNumber)} | ${v(business.taxNumber)}`],[{EN:"Contact and disputes",HU:"Kapcsolat és vitarendezés",DE:"Kontakt und Streitbeilegung"}[lang],`${v(business.complaintAddress)} | ${v(business.conciliationBody)} | ${v(business.conciliationContact)}`],[{EN:"Service providers",HU:"Szolgáltatók",DE:"Dienstleister"}[lang],v(business.processorStatement[lang])]]};
}
export function durableTerms(lang:PolicyLanguage){return [`FLOWSTATE RACING / ${business.policyVersion}`, ...[...policies(lang).TERMS,...policies(lang).DELIVERY].map(([h,t])=>`${h}\n${t}`)].join("\n\n");}
