export const ui = {
  EN: {
    concept: "DESIGN CONCEPT", price: "PROVISIONAL PRICE / CONCEPT", size: "Size", oneSize: "ONE SIZE", added: "Added to your bag", openBag: "Open bag", less: "Decrease quantity", more: "Increase quantity", close: "Close", menu: "Menu", navigation: "Main navigation", skip: "Skip to collection",
    fit: "FIT REFERENCE", fitText: "Oversized streetwear concepts. Verified measurements, model photography and video follow production samples. These garments are not protective motorcycle equipment.", previous: "Previous look", next: "Next look", preorder: "PLANNED PRE-ORDER MODEL", closed: "The first drop is taking shape. Email registration opens soon. Ordering is not available yet.", signupError: "We couldn't submit your request. Please try again shortly.", signupRate: "Too many attempts. Please wait a minute before trying again.", checkInbox: "CHECK YOUR INBOX", inbox: "If this address is eligible, a confirmation email is on its way. Follow its link to finish subscribing. Check your spam folder too.", consent: "I want FLOWSTATE RACING drop news and early-access emails. I can unsubscribe at any time.", privacyLink: "Privacy notice", sending: "SENDING…", sticker: "Sticker concepts designed alongside the jet tag. Download the scannable QR print proof.", print: "QR STICKER / PRINT PROOF", footer: ["TERMS", "PRIVACY", "COOKIES", "SHIPPING & RETURNS", "IMPRINT"], soon: "SOON", origin: "DESIGNED IN HUNGARY / 47°N", disclaimer: "RIDE RESPONSIBLY. AI CAMPAIGN CONCEPT.", affiliation: "NO AFFILIATION WITH EQUIPMENT BRANDS.", mockup: "AI design mockup, not a production sample", details: ["OVERSIZED · DESIGN CONCEPT", "BOXY FIT · CYBERSIGIL BACK PRINT", "EMBROIDERED JET TAG · DESIGN CONCEPT"],
    manifesto: { label: "MANIFESTO / 001", kicker: "THE WORLD GOES QUIET.", title: "YOU STAY", emphasis: "PRESENT.", intro: "A visor down. A breath held. The noise in your head finally falls away.", focus: "Picture the end of a circuit straight at 300 km/h: wind, engine, braking marker. Yesterday and tomorrow feel far away. That image captures the intensity behind FLOWSTATE. For us, flow is the rhythm between awareness, practice and instinct. Every input has a purpose. You are completely here.", origin: "47°N marks our roots in Hungary, in the heart of Central Europe. A latitude carried from our first ideas to every piece we make. European division. Hungarian beginning.", memory: "FOREVER YOUNG is for the riders who stay with us after their last ride. The names, the friendships, the stories we carry forward. Remember the people. Look after the ones still beside you.", focusLabel: "01 / THE STATE", originLabel: "02 / THE ORIGIN", memoryLabel: "03 / THE PEOPLE", note: "Circuit imagery. Flow is a state of attention, not a speed target. Tunnel vision is not the same as flow.", signature: "MADE OF FOCUS. ROOTED AT 47°N." }
  },
  HU: {
    concept: "LÁTVÁNYTERV", price: "TERVEZETT ÁR / LÁTVÁNYTERV", size: "Méret", oneSize: "EGY MÉRET", added: "A kosárba került", openBag: "Kosár megnyitása", less: "Mennyiség csökkentése", more: "Mennyiség növelése", close: "Bezárás", menu: "Menü", navigation: "Fő navigáció", skip: "Ugrás a kollekcióhoz",
    fit: "FAZON ÉS HANGULAT", fitText: "Oversized streetwear látványtervek. A pontos mérettáblázat, modellfotók és videók a gyártási minták után érkeznek. Ezek nem motoros védőruházati termékek.", previous: "Előző kép", next: "Következő kép", preorder: "TERVEZETT ELŐRENDELÉS", closed: "Alakul az első drop. Az emailes feliratkozás hamarosan nyílik. Rendelést még nem lehet leadni.", signupError: "Nem sikerült elküldeni a kérést. Próbáld újra kicsit később.", signupRate: "Túl sok próbálkozás. Várj egy percet, majd próbáld újra.", checkInbox: "NÉZD MEG AZ EMAILJEIDET", inbox: "Ha a címre küldhető megerősítés, hamarosan megérkezik az email. A benne lévő linkkel fejezheted be a feliratkozást. Nézd meg a spam mappát is.", consent: "Kérem a FLOWSTATE RACING drop híreit és a korai hozzáférésről szóló emailjeit. Bármikor leiratkozhatok.", privacyLink: "Adatkezelési tájékoztató", sending: "KÜLDÉS…", sticker: "A jet tag mellé tervezett matricák. Töltsd le a beolvasható QR-matrica nyomtatási tervét.", print: "QR-MATRICA / NYOMTATÁSI TERV", footer: ["ÁSZF", "ADATKEZELÉS", "SÜTIK", "SZÁLLÍTÁS ÉS ELÁLLÁS", "IMPRESSZUM"], soon: "HAMAROSAN", origin: "MAGYARORSZÁGON TERVEZVE / 47°N", disclaimer: "MOTOROZZ FELELŐSEN. AI-LÁTVÁNYTERVEK.", affiliation: "NINCS KAPCSOLAT A FELSZERELÉSMÁRKÁKKAL.", mockup: "AI-látványterv, nem gyártási minta", details: ["OVERSIZED · LÁTVÁNYTERV", "BOXY FAZON · CYBERSIGIL HÁTNYOMAT", "HÍMZETT JET TAG · LÁTVÁNYTERV"],
    manifesto: { label: "MANIFESZTÓ / 001", kicker: "ELHALKUL A VILÁG.", title: "TE JELEN", emphasis: "VAGY.", intro: "Lehajtott plexi. Egy visszatartott lélegzet. A fejedben végre elcsendesedik a zaj.", focus: "Képzeld el egy versenypálya célegyenesének végét 300 km/h-nál: szél, motorhang, féktávjelző. A tegnap és a holnap távolinak tűnik. Ebből az intenzitásból születik a FLOWSTATE hangulata. Nekünk a flow az éberség, a gyakorlás és az ösztön közös ritmusa. Minden mozdulatnak célja van. Teljesen itt vagy.", origin: "A 47°N a magyarországi gyökereinket jelöli, Közép-Európa szívében. Egy szélességi kör, amely az első ötlettől minden darabunkat végigkíséri. Európai divízió. Magyar kezdet.", memory: "A FOREVER YOUNG azoknak a motorosoknak szól, akik az utolsó útjuk után is velünk maradnak. Nevek, barátságok, történetek, amelyeket továbbviszünk. Emlékezz rájuk. Vigyázz azokra, akik még melletted vannak.", focusLabel: "01 / AZ ÁLLAPOT", originLabel: "02 / A GYÖKEREK", memoryLabel: "03 / AZ EMBEREK", note: "Versenypályás kép. A flow figyelmi állapot, nem sebességcél. A csőlátás nem azonos a flow-val.", signature: "FÓKUSZBÓL SZÜLETETT. 47°N-EN GYÖKEREZIK." }
  },
  DE: {
    concept: "DESIGNENTWURF", price: "VORLÄUFIGER PREIS / ENTWURF", size: "Größe", oneSize: "EINHEITSGRÖSSE", added: "Zum Warenkorb hinzugefügt", openBag: "Warenkorb öffnen", less: "Menge verringern", more: "Menge erhöhen", close: "Schließen", menu: "Menü", navigation: "Hauptnavigation", skip: "Zur Kollektion springen",
    fit: "PASSFORM & STIL", fitText: "Oversized-Streetwear als Designkonzept. Genaue Maße, Modelfotos und Videos folgen nach den Produktionsmustern. Diese Kleidung ist keine Motorradschutzkleidung.", previous: "Vorheriges Bild", next: "Nächstes Bild", preorder: "GEPLANTES VORBESTELLMODELL", closed: "Der erste Drop nimmt Form an. Die E-Mail-Anmeldung öffnet bald. Bestellungen sind noch nicht möglich.", signupError: "Deine Anfrage konnte nicht gesendet werden. Bitte versuche es gleich noch einmal.", signupRate: "Zu viele Versuche. Bitte warte eine Minute.", checkInbox: "PRÜFE DEIN POSTFACH", inbox: "Wenn an diese Adresse eine Bestätigung gesendet werden kann, erhältst du bald eine E-Mail. Schließe deine Anmeldung über den enthaltenen Link ab. Prüfe auch deinen Spamordner.", consent: "Ich möchte Drop-News und Early-Access-E-Mails von FLOWSTATE RACING erhalten. Ich kann mich jederzeit abmelden.", privacyLink: "Datenschutzhinweise", sending: "WIRD GESENDET…", sticker: "Stickerentwürfe passend zum Jet Tag. Lade die scanbare QR-Druckvorlage herunter.", print: "QR-STICKER / DRUCKENTWURF", footer: ["AGB", "DATENSCHUTZ", "COOKIES", "VERSAND & WIDERRUF", "IMPRESSUM"], soon: "BALD", origin: "IN UNGARN ENTWORFEN / 47°N", disclaimer: "FAHRE VERANTWORTUNGSVOLL. KI-KAMPAGNENENTWURF.", affiliation: "KEINE VERBINDUNG ZU DEN AUSRÜSTUNGSMARKEN.", mockup: "KI-Designentwurf, kein Produktionsmuster", details: ["OVERSIZED · DESIGNENTWURF", "BOXY FIT · CYBERSIGIL-RÜCKENDRUCK", "BESTICKTER JET TAG · DESIGNENTWURF"],
    manifesto: { label: "MANIFEST / 001", kicker: "DIE WELT WIRD STILL.", title: "DU BLEIBST", emphasis: "IM JETZT.", intro: "Visier zu. Ein angehaltener Atemzug. Der Lärm in deinem Kopf wird endlich leise.", focus: "Stell dir das Ende einer Rennstrecken-Geraden bei 300 km/h vor: Wind, Motor, Bremspunkt. Gestern und morgen fühlen sich weit weg an. Dieses Bild prägt die Intensität von FLOWSTATE. Für uns entsteht Flow im Zusammenspiel von Aufmerksamkeit, Übung und Instinkt. Jeder Impuls hat einen Sinn. Du bist ganz hier.", origin: "47°N steht für unsere Wurzeln in Ungarn, im Herzen Mitteleuropas. Ein Breitengrad, der uns von der ersten Idee bis zu jedem Kleidungsstück begleitet. Europäische Division. Ungarischer Ursprung.", memory: "FOREVER YOUNG ist für die Menschen, die nach ihrer letzten Fahrt bei uns bleiben. Namen, Freundschaften und Geschichten, die wir weitertragen. Erinnere dich an sie. Achte auf die, die noch an deiner Seite fahren.", focusLabel: "01 / DER ZUSTAND", originLabel: "02 / DER URSPRUNG", memoryLabel: "03 / DIE MENSCHEN", note: "Rennstreckenmotiv. Flow ist ein Zustand der Aufmerksamkeit, kein Geschwindigkeitsziel. Tunnelblick ist nicht dasselbe wie Flow.", signature: "AUS FOKUS ENTSTANDEN. BEI 47°N VERWURZELT." }
  }
};
